/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.kubode.playground.renovate.gradle

class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }
}
